### PR TITLE
better logging

### PR DESCRIPTION
**Pull request by koaning**
an attempt at adressing: https://github.com/godatadriven/asekuro/issues/18 

i've kept the logging at a verbose level at all times now. might want to add this as a setting later, but i can't imagine i'd ever want to run it in non-verbose mode. either way: here's a small simple fix.

### CODE REVIEW

**Comment by NielsZeilemaker** [comment]
Instead of switching to logging, just call `logger = logging.getLogger('asekuro')` in all of the methods. It's cheap enough to do so

**Comment by NielsZeilemaker** [comment]
And configure the logging in the
```
if __name__ == "__main__":
```
section instead of __init__.py

**Comment by NielsZeilemaker** [comment]
Finally, remove the `sys.exit(2)`. That's really bad practice. raise an RuntimeError instead.
If I was using asekuro as a library, than the sys exit would kill my main program

**Comment by hgrif** [comment]
This one should be now be good to go! `sys.exit(2)` can go in a separate PR (or fix it manually).

**Comment by hgrif** [comment]
@koaning: Could you merge this?

**Pull request merged**
